services:
  mongo:
    image: mongo:latest
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://root:root@mongo:27017"
      MONGO_DATABASE: "go-example"
      SERVER_PORT: "8080"
    restart: on-failure

volumes:
  mongo_data: